version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
        context: ./Datenbank
        dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
        context: ./api-backend
        dockerfile: Dockerfile
    environment:
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
    volumes:
      - ./:/usr/src/app
    scale: 3
    links:
      - db
    depends_on:
      - db
    restart: always
  nginx:
    restart: always
    build: ./nginx 
    ports:
    - "4000:80"
    depends_on:
      - db
      - backend
volumes:
  db:
