version: '3.1'

services:
  db:
    image: postgres:latest
    build:
        context: ./Datenbank
        dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
        context: ./api-backend
        dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    scale: 3
    links:
      - db
    depends_on:
      - db
    restart: always
  nginx:
    build: ./nginx 
    ports:
    - "3000:80"
    depends_on:
      - db
      - backend
volumes:
  db:
