version: '3.1'

services:
  db:
    image: postgres:latest
    build:
        context: ./Datenbank
        dockerfile: Dockerfile
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: SicheresPasswort!
      POSTGRES_DB: pong_daten
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
        context: ./api-backend
        dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      PGHOST: db
      PGUSER: testuser
      PGPASSWORD: SicheresPasswort!
      PGDATABASE: pong_daten
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    restart: always
  game:
    build:
        context: ./game
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - backend
    restart: always
    depends_on:
      - backend
volumes:
  db:
