version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: project_pong
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: SicheresPasswort!
      POSTGRES_DB: pong_daten
    ports:
      - "5432:5432"
    volumes:
      - ./pong_daten_dump.sql:/docker-entrypoint-initdb.d/pong_daten_dump.sql
      
volumes:
  postgressql: