@startuml
title "show lobby with authentication"
skinparam defaultFontSize 30
skinparam componentFontSize 30
skinparam actorFontSize 30
skinparam noteFontSize 30
skinparam sequenceParticipantFontSize 30
skinparam sequenceMessageFontSize 30
skinparam titleFontSize 30
actor player
box "game services"
participant "auth.ts" as auth
participant "api controller" as gs
participant "raum.ts" as lo
end box
database database as db

player -> auth: /api/raum/\nAuthorization: Bearer <token>
activate auth
auth -> auth: verify(token)
alt token valid
    auth -> player: token valid
    deactivate auth
    player -> gs: show_lobby(filters)
    activate gs
    gs -> lo: dbAllRooms()
    activate lo
    lo -> db: SELECT r.*,s.name as user1, sp.name as user2 FROM\n Raum r \n LEFT JOIN "user" s  on s.user_id=r.user_id1 \n LEFT  JOIN "user" sp on sp.user_id=r.user_id2;
    activate db
    db -> lo: lobbies[]
    deactivate db
    lo -> gs: lobbies[]
    deactivate lo
    gs -> player: lobbies[]
    deactivate gs
else token invalid
    auth -> player: Please authenticate
    deactivate auth
end
@enduml
